<?php if ($this->zfcUserIdentity()):?>
<ul class="nav navbar-nav navbar-right">
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $this->zfcUserIdentity()->getEmail();?> <span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">
      <li><a href="<?=$this->url('zfcuser');?>">Profile</a></li>
      <li class="divider"></li>
      <li><a href="<?=$this->url('zfcuser/logout');?>">Logout</a></li>
    </ul>
  </li>
</ul>
<?php else: ?>
  <ul class="nav navbar-nav navbar-right">
    <li class="dropdown">
      <a href="<?=$this->url('zfcuser/login');?>">Login</a>
    </li>
  </ul>
<?php endif;?>