<div class="row">
  <div class="col-md-1">
    <?php echo $this->gravatar($this->zfcUserIdentity()->getEmail()) ?>
  </div>
  <div class="col-md-11">
    <h3><?php echo $this->translate('Hello'); ?>, <?php echo $this->zfcUserDisplayName() ?>!</h3>
  </div>
</div>
<hr />
<div class="row">
  <form role="form">
    <div class="form-group col-md-4">
      <label for="email">Email</label>
      <input class="form-control" type="text" />
    </div>
    <div class="form-group col-md-4">
      <label for="email">Email</label>
      <input class="form-control" type="text" />
    </div>
    <div class="form-group col-md-4">
      <label for="email">Email</label>
      <input class="form-control" type="text" />
    </div>
</div>
<div class="row">
  <form role="form">
    <div class="form-group col-md-4">
      <label for="email">Email</label>
      <input class="form-control" type="text" />
    </div>
    <div class="form-group col-md-4">
      <label for="email">Email</label>
      <input class="form-control" type="text" />
    </div>
    <div class="form-group col-md-4">
      <label for="email">Email</label>
      <input class="form-control" type="text" />
    </div>
</div>
<div class="row">
  <form role="form">
    <div class="form-group col-md-4">
      <label for="email">Email</label>
      <input class="form-control" type="text" />
    </div>
    <div class="form-group col-md-4">
      <label for="email">Email</label>
      <input class="form-control" type="text" />
    </div>
    <div class="form-group col-md-4">
      <label for="email">Email</label>
      <input class="form-control" type="text" />
    </div>
</div>
<div class="form text-right">
    <button type="submit" class="btn btn-default">Submit</button>
</div>
