<h1><?php echo $this->translate('Register'); ?></h1>

<?php
if (!$this->enableRegistration) {
    echo $this->translate('Registration is disabled');
    return;
}
$form = $this->registerForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/register'));
$form->setAttribute('method', 'post');
?>

<?php echo $this->form()->openTag($form) ?>
    <?php foreach ($form as $element): ?>
      <div class="row">
        <div class="form-group col-md-3">
        <?php if (!$element instanceof Zend\Form\Element\Button): ?>
            <?php echo $this->formLabel($element) ?>
        <?php endif ?>
        <?php if ($element instanceof Zend\Form\Element\Button):
            $element->setAttribute('class', 'btn btn-info'); ?>
            <?php echo $this->formButton($element) ?>
        <?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
            <?php echo $this->formCaptcha($element) . $this->formElementErrors($element) ?>
        <?php else:
            $element->setAttribute('class', 'form-control');?>
            <?php echo $this->formInput($element) . $this->formElementErrors($element) ?>
        <?php endif ?>
      </div>
    </div>
    <?php endforeach ?>
    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
    <?php endif ?>
<?php echo $this->form()->closeTag() ?>
